automenta/spacegraphjs

example-bundled-usage.html
example-custom-webgl-node.html
example-keystone.html
js/demo-launcher.js
package-lock.json

This commit addresses issues with the gh-pages index.html site and demo examples, ensuring a consistent import strategy for the SpaceGraph library and its dependencies, particularly Three.js.
Key changes:
- Modified `js/demo-launcher.js` to correctly instantiate `SpaceGraphZUI.SpaceGraph` from the UMD bundle, resolving the `SpaceGraphZUI is not a constructor` error on `index.html`.
- Updated `example-keystone.html` to use the `dist/spacegraph.umd.js` bundle and rely on the Three.js version bundled within it, removing separate CDN imports for Three.js.
- Corrected `example-custom-webgl-node.html` to import `THREE` from the `dist/spacegraph.esm.min.js` bundle instead of attempting an incorrect static access.
- Updated `example-bundled-usage.html` by removing its import map entries for …

Fix gh-pages and demo import strategies

---

example-3d-scene.html
example-app-nodes.html
example-bundled-usage.html
example-centralized-config.html
example-custom-node.html
example-custom-webgl-node.html
example-dashboard.html
example-dynamic-dashboard.html
example-dynamic-updates.html
example-event-emitter.html
example-hierarchical-data.html
example-inter-node-communication.html
example-keystone.html
example-mindmap.html
example-registered-node-html.html
example-registered-node-webgl.html
example-shape-nodes.html
example-simple-counter-app-node.html
example-text-nodes.html
index.html

Introduces import maps in all example HTML files and the main index.html to ensure that external dependencies (Three.js, GSAP) are correctly resolved by the browser when loading ES modules directly. This addresses the "Uncaught TypeError: Failed to resolve module specifier" error that occurred after previous changes to standardize library imports.
Key changes:
- Defined an import map that points "three", "three/addons/", and "gsap" to their respective CDN URLs (unpkg.com).
- Added this import map to the <head> section of `index.html`.
- Added the same import map to the <head> section of all `example-*.html` files.
The build processes (`npm run build`, `npm start`, `npm run build:gh-pages`) have been verified to complete successfully with these changes, and the output `docs` folder now …

Fix: Add import maps to resolve external dependencies in demos

---

js/ui/UIManager.js

UIManager.js has been updated to correctly manage and provide the DOM element for the ContextMenuManager.
Changes include:
- UIManager constructor now ensures a context menu DOM element is available, creating one if not provided via uiElements.contextMenuContainer.
- Added getDomElement(name) method to UIManager to allow components to retrieve their managed DOM elements.
- ContextMenuManager instantiation in UIManager updated to align with its constructor, as it now gets its element via uiManager.getDomElement.
This resolves the runtime TypeError: "this.uiManager.getDomElement is not a function" that occurred when initializing ContextMenuManager.
Note: Automated tests are currently timing out, and the specific test file for ContextMenuManager (ContextMenuManager.test.js) was found to be …

Fix: Resolve TypeError for uiManager.getDomElement

---

dist-demo/index.html
vite.config.js

- Create vite.config.js to set base: '/spacegraphjs/' for the demo build.
- This ensures that asset paths in the generated index.html are correctly prefixed, resolving 404 errors when deployed to GitHub Pages as a project page.
- Verified build output and existing build scripts.

Fix: Configure Vite base path for gh-pages demo

---

package.json

This commit significantly simplifies the `build:gh-pages` npm script to make the GitHub Pages deployment more robust and less prone to build failures.
Changes:
- Removed the Vite-based demo build (`npm run build:demo`) from the gh-pages deployment process.
- The script now copies the root `index.html` file to `docs/index.html`.
- The entire `src/` directory is copied to `docs/src/`. This allows the `docs/index.html` to use its existing relative paths (`src/...`) to load CSS and JavaScript modules directly from the source files.
- The library build (`npm run build` outputting to `dist/`) is still performed, and its contents are copied to `docs/lib/` for potential use or reference.
- JSDoc generation to `docs/api/` is preserved.
- Removed complex `rm` commands from the script to prevent …

Fix: Simplify gh-pages build, use static HTML and src files

---

.github/workflows/gh-pages.yml
package.json

This commit implements a minimal GitHub Actions workflow to deploy the root `index.html` and its referenced `src/` directory contents.
Changes:
- `.github/workflows/gh-pages.yml`:
- Removed Node.js setup and `npm ci` steps.
- The 'Build GitHub Pages site' step now directly runs shell commands: `rm -rf docs && mkdir -p docs/src && cp index.html docs/index.html && cp -R src/. docs/src/`
- This prepares a `docs/` directory with `index.html` and `docs/src/`.
- Verification step lists contents of `docs/` and `docs/index.html`.
- `package.json`:
- The `build:gh-pages` script is now an echo message, as its functionality has been moved directly into the workflow.
This approach aims to deploy the static site content with the fewest possible dependencies and build steps within the Actions …

Fix: Minimal Actions deployment for static HTML and src

---

src/graph/CurvedEdge.js

Ensures `this.numPoints` in `CurvedEdge.js` is at least 1. This prevents `curve.getPoints()` from potentially returning an empty array or an insufficient number of points, which could lead to an `Invalid typed array length` error when `LineGeometry.setColors()` calculates buffer sizes based on vertex count.
The specific error `Invalid typed array length: -6` occurred when the geometry had 0 points, causing a calculation of `(0-1)*6 = -6` for an internal color buffer in `LineGeometry`. Setting a minimum of 1 segment (2 points) for `CurvedEdge` resolves this.

Fix: Prevent negative numPoints in CurvedEdge

---

eslint.config.js
package-lock.json
package.json
src/rendering/InstancedMeshManager.js
src/rendering/InstancedMeshManager.test.js
tsconfig.json

- Corrected the import path for GLTFLoader in InstancedMeshManager.js to align with the project's import map (using `three/addons/` via CDN).
- Updated the corresponding mock path in InstancedMeshManager.test.js.
- Added `eslint-plugin-import` to ESLint configuration.
- Configured `import/no-unresolved` rule to ignore CDN-based imports specified in the import map (e.g., `three`, `three/addons/`, `gsap`) while still validating other local and node_module imports.
- This resolves the browser TypeError related to GLTFLoader module resolution and provides a build-time/lint-time check against similar future errors.

Fix: Correct GLTFLoader import path and add ESLint import validation

---

index.html
src/ui/Metaframe.js

- Corrected the import path for CSS3DObject in src/ui/Metaframe.js to use 'three/addons/' prefix, aligning with the project's import map and resolving the module resolution error.
- Added 'chart.js' and 'postprocessing' to the import map in index.html to ensure these dependencies are correctly loaded from CDN for the demo page.
- Verified all other imports for consistency and correctness.

Fix: Correct CSS3DRenderer import path and update import map

---

src/ui/UIManager.js

The file src/ui/UIManager.js had an extraneous line `[end of src/ui/UIManager.js]` at the end, which caused a JavaScript syntax error during parsing. This commit removes the offending line.

Fix: Remove extraneous line causing syntax error in UIManager.js

---

src/ui/gizmos/TranslationGizmo.js

Replaced incorrect use of clampScalar on THREE.Color object with component-wise clamping to resolve TypeError in setHandleActive method.

Fix: Correct color clamping in TranslationGizmo

---

src/graph/nodes/DocumentNode.js
src/layout/RadialLayout.js
src/ui/UIManager.gizmo.test.js
src/ui/UIManager.js

- UIManager.gizmo.test.js:
- Disabled import/no-unresolved for Vitest mocks.
- Corrected THREE.Raycaster mocking to use vi.spyOn (fixes no-import-assign).
- Removed unused variable.
- UIManager.js:
- Fixed no-undef errors in _getTargetInfo method.
- no-case-declarations believed to be fixed by prior brace additions.
- DocumentNode.js & RadialLayout.js:
- Commented out console.warn calls.
- FractalUIElements.js:
- no-unused-vars for 'index' likely resolved by prior rename to '_index' (which is used).
Note: `npm run lint` timed out, preventing full verification of all ESLint fixes via the toolchain.

Fix: Address multiple ESLint errors and warnings

---

src/ui/UIManager.gizmo.test.js
src/ui/UIManager.js

- Corrected relative import paths in src/ui/UIManager.gizmo.test.js.
- Attempted to fix no-case-declarations warnings in src/ui/UIManager.js by refactoring the relevant switch case, but warnings persist.
- A Prettier error for a missing newline at EOF and a whitespace error also remain due to tool limitations in applying these specific fixes.

Fix: Resolve import/no-unresolved error in UIManager.gizmo.test.js

---

src/camera/Camera.js
src/plugins/CameraPlugin.js

- Added `getAvailableCameraModes` method to `CameraPlugin.js` to provide a list of available camera modes.
- Exported `CAMERA_MODES` constant from `Camera.js` and imported it into `CameraPlugin.js` to ensure a single source of truth for mode definitions.
- This resolves the runtime error `r.getAvailableCameraModes is not a function` that occurred during HUD initialization.

Fix: Resolve getAvailableCameraModes is not a function error

---

src/zoom/FractalZoomManager.js

Addresses a TypeError during initialization where FractalZoomManager was attempting to call `this.space.getNodes()` and `this.space.getEdges()`. These methods do not exist on the SpaceGraph instance (`this.space`).
The fix updates these calls to correctly use the PluginManager to access NodePlugin and EdgePlugin for retrieving nodes and edges:
- `this.space.plugins.getPlugin('NodePlugin')?.getNodes()`
- `this.space.plugins.getPlugin('EdgePlugin')?.getEdges()`
Includes null checks for robustness.

Fix: Correct node/edge access in FractalZoomManager

---

src/performance/PerformanceManager.js
src/plugins/NodePlugin.js

The 'node:added' event was being emitted by NodePlugin with only the node instance as an argument. However, listeners like PerformanceManager._onNodeAdded expected (nodeId, nodeInstance). This mismatch caused the 'node' parameter in PerformanceManager._onNodeAdded to be undefined, leading to a TypeError when attempting to access node.object3d in InstanceManager.registerObject.
This commit corrects the event emission in NodePlugin.addNode to pass both nodeId and nodeInstance.
Additionally, a defensive check for a null/undefined object parameter has been added to InstanceManager.registerObject to prevent potential errors if it's ever called with an undefined object from other paths.

Fix: Correct arguments for node:added event

---

src/layout/ForceLayout.js
src/plugins/LayoutPlugin.js

- Corrected `node:added` event listener in `LayoutPlugin` to use `nodeInstance` instead of `nodeId`.
- Added defensive checks in `ForceLayout.addNode` to handle cases where node position or other properties might be undefined, preventing TypeError.
- Verified argument handling for related `node:removed`, `edge:added`, and `edge:removed` events.

Fix: Handle missing node position in ForceLayout

---

src/plugins/MinimapPlugin.js

Prevent TypeError when a node's data or color property is undefined by using a default color for the minimap proxy in `_addNodeProxy` and `_updateNodeProxies` in `src/plugins/MinimapPlugin.js`.

Fix: Handle undefined node color in MinimapPlugin

---

src/ui/hud/AdvancedHudManager.js

Changed `getCurrentLayout()` to `getActiveLayoutName()` in `_updateMenuStatusItems` to prevent a TypeError and correctly display the active layout's name in the HUD menu.
The original call `layoutManager?.getCurrentLayout()` was incorrect as the method is named `getActiveLayout()`. Furthermore, accessing `currentLayout?.name` was unreliable as not all layout objects (e.g., ForceLayout, hybrid proxy) expose a `name` property. Using `layoutManager.getActiveLayoutName()` directly retrieves the intended display string.

Fix: Correct method call for layout name in AdvancedHudManager

---

src/examples/demos/allFeaturesDemo.js
src/plugins/FractalZoomPlugin.js
src/ui/hud/AdvancedHudManager.js
src/ui/hud/HudManager.js

Replaced all instances of `nodePlugin.getNodeCount()` with `nodePlugin.getNodes().size` to correctly retrieve the number of nodes. Added null checks to prevent errors if `nodePlugin` or `getNodes` is undefined.
Enhanced error handling in `FractalZoomPlugin.js` by adding try...catch blocks around critical sections such as plugin initialization, content adapter creation/removal, and plugin disposal. This should make the plugin more resilient to unexpected issues and prevent them from crashing the application.

Fix: Correct getNodeCount usage and improve error handling
